clear
echo
echo $cy"================================================================"
echo $pu"Github     : https://github.com/AtanCube"
echo $pu"WhatsApp   : +6283179472578"
echo $pu"Instagram  : https://www.instagram.com/rakhmatan_nabil.n"
echo $pu"Telegram   : https://t.me/AtanCyberHack"
echo $cy"================================================================"
echo
echo $cy"   ╔═══════════╗"
echo $cy" ╔═╝███████████╚═╗"
echo $cy"╔╝███████████████╚╗"
echo $cy"║█████████████████║"
echo $cy"║█████████████████║   | SELAMAT ANDA TERTIPU    |"
echo $cy"║█████████████████║   | 2020 KOK GRATISAN :D    |"
echo $cy"║█╔█████████████╗█║   | MODAL DIKIT LAH, BAHAHA |"
echo $cy"╚╦╝███▒▒███▒▒███╚╦╝   | TERCIUM AROMA KEKESALAN |"
echo $cy"╔╝██▒▒▒▒███▒▒▒▒██╚╗   | TIDAK ADA WIFI          |"
echo $cy"║██▒▒▒▒▒███▒▒▒▒▒██║   | YANG AMAN CUK :v        |"
echo $cy"║██▒▒▒▒▒███▒▒▒▒▒██║"
echo $cy"║██▒▒▒▒█████▒▒▒▒██║"
echo $cy"╚╗███████████████╔╝"
echo $cy" ╚══╦╝██▒█▒██╚╦══╝"
echo $cy"    ║█████████║"
echo $cy"    ║█║██║██║█║"
echo $cy"    ╚═╩══╩══╩═╝"

